name: Daily Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a la medianoche UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Configura la versión de Python según tus necesidades

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client beautifulsoup4 requests

      - name: Run script
        run: python scraper.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
